/***********************************************************************/
/*                                                                     */
/*  FILE        :en4.c                                                 */
/*  DATE        :Sat, Jun 11, 2022                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3694F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  

#include "iodefine.h"
#include "timerA.h"
#include "led.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	
	while (1){
		InitLED();
        iniTimerA();
	}

}

#ifdef __cplusplus
void abort(void)
{

}
#endif
